### ISSUE TITLE
Bump major when bumping dependencies to a new major

### ISSUE THREAD

**Issue by AltarBeastiful** [kugacz/nj-request-scope#8]
Hi Marek,

I noticed from 1.0.5 to 1.0.6 the dependencies to nesjts packages have been bumped from v8 to v9.
It's usually good pratice to issue a new major release when that happens, especially with nestjs. As npm deps resolution might install both v9 and v8 version without any modification in package.json.

No real work needed, but it might be useful for next major nestjs migration.
Apart maybe documenting how to install your extension for Nestjs v8 : 
```bash
npm install --save --save-exact nj-request-scope@1.0.5
```

**Comment by kugacz** [comment]
Hi Rémi,

Good point. Thank you for your feedback :)
Unfortunately, version 1.0.5 has some dependencies with vulnerabilities. 
So it might be a good idea to separate the two versions right away according to your suggestion.
I could create a new 1.0.7 version with NestJs v8 dependency and release a new major 2.0.0 with Nest Js v9.
What do you think?

**Comment by AltarBeastiful** [comment]
That would be great ! 
I had to force thé version to 1.0.5 in my code and would greatly appreciate a sécurité update release.

**Comment by kugacz** [comment]
I made some research and decided to switch to peer dependencies.
Now it is possible to have your own NestJS version (v8.x or v9.x) in the root project and `nj-reqest-scope` will work with this root version instead of installing a separate one.
Please, let me know if it works for you.
